### ISSUE TITLE
Login problem  and how to init database

### ISSUE THREAD

**Issue by masterchen** [Eastrall/Rhisis#126]
1、 i'm using sql server , can you tell me how to do database migration ,I run "update-database"  with nuget Managerment command line under project "Data" intent to init database , is it right ? and how to init database  and what's content should in database?
2. If i start login bat  directly also have problem:

I changed the database json file like this:
{
  "host": "127.0.0.1",
  "port": 3306,
  "username": "sa",
  "password": "123456",
  "database": "rhisis",
  "provider": 1
}

Then start project "login " module in vs 2017 ,  but see the following error , i know this may caused by SQl problem. can you give some more hint :

[2018-11-04 13:03:45.7319] [DEBUG] [LoginServer] Loading server configuration from 'config/login.json'...
[2018-11-04 13:03:46.0931] [TRACE] [LoginServer] Host: 127.0.0.1, Port: 23000, MaxNumberOfConnections: 1000, Backlog: 100, BufferSize: 4096
[2018-11-04 13:03:46.1851] [DEBUG] [LoginServer] Loading database configuration from 'config/database.json'...
[2018-11-04 13:03:47.9745] [FATAL] MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.

**Comment by Eastrall** [comment]
Hi, you can try using the `Rhisis.Installer` tool to configure the database and create the first admin user.
When you open the `Rhisis.Installer`, click on the database configuration button and follow the steps to configure the database access and create the user. Once you finished configurating the database and your account, click the OK button, then the "Start Install" button.

![image](https://user-images.githubusercontent.com/4021025/47965222-c1e1d180-e044-11e8-8117-39e8d1bfb531.png)

This will create the database, run the migrations and create your account.

As for your error, you are trying to connect to a MySQL server instead of a MsSQL instance. There is the list of the providers: https://github.com/Eastrall/Rhisis/blob/develop/src/Rhisis.Database/DatabaseProvider.cs

⚠️ Remember that only MsSQL and MySQL providers work.

**Comment by masterchen** [comment]
Hi, thanks for you guide, after clicking  "Start install", there exception happened, my database is mssqlserver .
System.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0

**Comment by masterchen** [comment]
By the way , the connection test show that "The connaction has succeeded"

**Comment by Eastrall** [comment]
Interesting behavior. Did you created the database before executing the `Rhisis.Installer` tool ?
If so, delete your database and restart the installation tool. The tool will create the database for you and also create one account.

**Comment by HaLenSoft** [comment]
I tried the installation tool with a MySql database. I noticed that creating the database works. Only creating an account does not work. After I created the account by hand and had created a character. Now I get a PRE_JOIN error message when connecting

```
Packet handle error from 127.0.0.1:53132. Rhisis.Core.Exceptions.RhisisPacketException: An error occured during the execution of packet handler: PRE_JOIN ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Rhisis.Cluster.LoginProtect.GetNumPadToPassword(Int32 idNumPad, Int32 secretNum) in MyPath\LoginProtect.cs:line 226
   at Rhisis.Cluster.ClusterHandler.OnPreJoin(ClusterClient client, INetPacketStream packet) in MyPath\ClusterHandler.cs:line 232
   at Rhisis.Network.PacketHandler`1.Invoke(T invoker, INetPacketStream packet, Object packetHeader) in MyPath\PacketHandlers.cs:line 68
   --- End of inner exception stack trace ---
   at Rhisis.Network.PacketHandler`1.Invoke(T invoker, INetPacketStream packet, Object packetHeader) in MyPath\PacketHandlers.cs:line 72
   at Rhisis.Cluster.ClusterClient.HandleMessage(INetPacketStream packet) in MyPath\ClusterClient.cs:line 87 
[2019-01-16 20:35:23.0436] [DEBUG] [Rhisis.Cluster.ClusterClient]    at Rhisis.Cluster.LoginProtect.GetNumPadToPassword(Int32 idNumPad, Int32 secretNum) in MyPath\LoginProtect.cs:line 226
   at Rhisis.Cluster.ClusterHandler.OnPreJoin(ClusterClient client, INetPacketStream packet) in MyPath\ClusterHandler.cs:line 232
   at Rhisis.Network.PacketHandler`1.Invoke(T invoker, INetPacketStream packet, Object packetHeader) in MyPath\PacketHandlers.cs:line 68 
```

**Comment by johmarjac** [comment]
@HaLenSoft Does your client ask for a 2nd Password? You can enable/disable this behaviour in the `bin/config/ClusterServer.json`:
![image](https://user-images.githubusercontent.com/30114127/51277869-2fad6080-19d9-11e9-9479-c21de40ed48d.png)

**Comment by HaLenSoft** [comment]
Thanks, thats was the Problem.

**Comment by johmarjac** [comment]
> Thanks, thats was the Problem.

NP 👍

**Comment by Eastrall** [comment]
Hi, you can now use the Rhisis CLI program that is much easier to use than the GUI tool.
To do so, you should compile the solution using the `scripts/compile_solution.bat` and then go to the `bin` folder and execute the following command in a cmd or powershell:
```
$> ./rhisis-cli.bat database initialize
```

Closing issue.
